apiVersion: v2
name: prowlarr
description: A Helm chart for Prowlarr
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://prowlarr.com/
icon: https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/128.png
maintainers:
  - name: Yub0
    email: maintainer@example.com
