apiVersion: v2
name: prowlarr
description: A Helm chart for Prowlarr
type: application
version: 0.1.0
appVersion: "1.29.2"
home: https://prowlarr.com/
icon: https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/128.png
maintainers:
  - name: my-charts
    email: maintainer@example.com
